### ISSUE TITLE
trouble setting background color/image

### ISSUE THREAD

**Issue by aggieben** [ignism/nucleus-dark-ui#11]
I'm setting a background like this:

``` less
@reclaimed_wood: 'http://i.imgur.com/udi6zGt.png';

.pane {
    background: url(@reclaimed_wood);
    background-size: cover;
}

.editor {
    background-color: rgba(0, 0, 0, 0.6);
}
```

This works ok with the `atom-dark` ui theme, but not with this one.
