### ISSUE TITLE
the UPPERCASE patch

### ISSUE THREAD

**Issue by objectkit** [ignism/nucleus-dark-ui#111]
Hey - love nucleus. Any settings available to make uppercase letters optional?

**Comment by hathix** [comment]
Agreed — the uppercase letters are jarring to me because I've been used to lowercase letters. I love Nucleus but the uppercase letters aren't great in my mind.

**Comment by adamhollett** [comment]
This code in your `styles.less` will mostly get things back to normal:

``` less
button, select, .tab .title { text-transform: none !important; }
```
