### ISSUE TITLE
Modal & footer styles: colors & paddings

### ISSUE THREAD

**Issue by alex35mil** [ignism/nucleus-dark-ui#83]
I just updated to the most recent version and notice changes in modal & footer styles.

I've made some quick local overrides: 
- \+ ~10px to paddings for items in modals (imo needs some breathing room)
- darker background colors for modals (not really a concern, just used to it)
- darker colors for footer (brighter one captures more attention than it should imo)

Might be something to consider for the theme core.

Theme as is:

![screen shot 2016-10-13 at 15 59 54](https://cloud.githubusercontent.com/assets/4244251/19341127/ba8a0eb6-915e-11e6-9ed1-49a3d0bee952.png)

Theme w/ overrides:

![screen shot 2016-10-13 at 15 58 36](https://cloud.githubusercontent.com/assets/4244251/19341141/cba0e5e4-915e-11e6-9cd6-2d5399083384.png)

Overrides:

``` less
@panels-bg-color: #2a2a2a;
@panels-top-label-margins: 20px 20px 0;

atom-workspace {
  .overlay,
  atom-panel.modal {
    background-color: @panels-bg-color;

    .tree-view-dialog label:first-child {
      margin: @panels-top-label-margins;
    }
  }

  .overlay > * > *,
  atom-panel.modal > * > * {
    &:not(.list-group) {
      margin: 20px;
    }

    &.info-message {
      margin: @panels-top-label-margins;
    }
  }

  .overlay .list-group li.list-nested-item > .list-item,
  atom-panel.modal .list-group li.list-nested-item > .list-item,
  .overlay .list-tree li.list-nested-item > .list-item,
  atom-panel.modal .list-tree li.list-nested-item > .list-item,
  .overlay .list-group li:not(.list-nested-item),
  atom-panel.modal .list-group li:not(.list-nested-item),
  .overlay .list-tree li:not(.list-nested-item),
  atom-panel.modal .list-tree li:not(.list-nested-item) {
    padding: 10px 20px;
  }

  .select-list ol.list-group li.two-lines .secondary-line,
  .select-list ol.list-group li.two-lines .secondary-line {
    color: inherit;

    .character-match {
      color: #fff;
    }
  }

  .footer .status-bar {
    background-color: @panels-bg-color;
  }
}
```
