### ISSUE TITLE
Proposal: Fixed project-root-header

### ISSUE THREAD

**Issue by oomathias** [ignism/nucleus-dark-ui#98]
Make the header of the tree view fixed (project's tiltle), so when you scroll you can still see which project is open.

<img width="279" alt="screenshot 37" src="https://cloud.githubusercontent.com/assets/465790/22345439/6664d6c8-e400-11e6-9cd8-12e7b8725f56.png">

I ended up doing this in my stylesheet, it's ugly but does the work.

 ```less
* {
  -webkit-font-smoothing: antialiased;
}

.tool-panel  {
  .tree-view-scroller {
    position: static;
  }
  .tree-view {
    position: static;
  }
  .project-root-header {
    position: absolute;
    top: -1px;
    width: 100%;
    background: #152026;
    border-bottom: 1px solid #10191e;
    box-sizing: border-box;
    z-index: 9999;
  }
  .project-root > .entries.list-tree {
    margin-top: 31px;
  }
}
```

**Comment by ignism** [comment]
I like this! I will implement it in the next patch

Although I need to figure out how to place it correctly, I am using a package that lists the files that I have open, and the project title is now hovering over that tool-panel.

**Comment by ignism** [comment]
got this working, but then when I add a background color to it, it is on top of the other panels.

```
.tree-view {
  position: relative;

  .project-root-header {
    position: fixed;
    margin-top: -32px;
    width: 100%;
    box-sizing: border-box;
    z-index: +1;
  }
  .project-root > .entries.list-tree {
    margin-top: 32px;
  }
}
```

**Comment by oomathias** [comment]
Yeah, that's why I said my solution was ugly.

Maybe something like that:
```css
atom-workspace-axis {
  z-index: +2;
}

.tree-view-resizer > .tree-view-scroller:not(:first-child) {
  padding: 0;
  border: none;
}

.tree-view {
  position: relative;
  .project-root.expanded:only-child {
    .project-root-header{
      position: fixed;
      left: 0;
      padding-left: 5px;
      width: 100%;
      margin-top: -32px;
      box-sizing: border-box;
      z-index: +1;
      background: #152026;
      border-bottom: 1px solid #10191e;
    }
    &> .entries.list-tree {
      margin-top: 32px;
    }
  }
}
```
[updated]
